#!/usr/bin/env python3
"""
Build BOL-BOT.exe and assemble a standalone release folder.

Usage (from BOL-BOT folder):
    python scripts/build_exe.py           # full build + release folder
    python scripts/build_exe.py --release-only   # reuse existing dist/ build
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASE_TEMPLATES = ROOT / "release"
LICENCE_DATA = ROOT / "src" / "utils" / "_licence_data.py"
TRIAL_DAYS = 14
_LICENCE_XOR_KEY = 0x5A3C91E7
DIST_APP = ROOT / "dist" / "BOL-BOT"
RELEASE_DIR = ROOT.parent / "BOL-BOT-Release"
EXE_NAME = "BOL-BOT.exe"

# Dev files copied into release when present (user's working config).
OPTIONAL_DEV_FILES = (
    "bol_credentials.json",
    "bol_token.json",
    "login.txt",
    "config/discord.yaml",
    "config/roundproxies.yaml",
    "tasks/tasks.yaml",
)


def write_licence_data() -> tuple[int, int]:
    build_unix = int(time.time())
    expiry_unix = build_unix + TRIAL_DAYS * 24 * 3600
    expiry_encoded = expiry_unix ^ _LICENCE_XOR_KEY
    LICENCE_DATA.write_text(
        f"""# Auto-generated by scripts/build_exe.py — do not edit manually.
BUILD_UNIX = {build_unix}
EXPIRY_ENCODED = {expiry_encoded}
TRIAL_DAYS = {TRIAL_DAYS}
""",
        encoding="utf-8",
    )
    return build_unix, expiry_unix


def ensure_pyinstaller() -> None:
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "pyinstaller>=6.0"],
            cwd=ROOT,
        )


def bundle_main_py() -> None:
    """Embed fresh src/ (incl. licence data) into single-file main.py before PyInstaller."""
    bundler = ROOT / "_bundle_main.py"
    if not bundler.is_file():
        raise FileNotFoundError(f"Missing {bundler}")
    subprocess.check_call([sys.executable, str(bundler)], cwd=ROOT)


def run_pyinstaller() -> None:
    spec = ROOT / "BOL-BOT.spec"
    if not spec.is_file():
        raise FileNotFoundError(f"Missing {spec}")
    subprocess.check_call(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(spec)],
        cwd=ROOT,
    )


def _copy_tree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst, ignore_errors=True)
    shutil.copytree(src, dst)


def _copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _playwright_browser_revisions() -> tuple[str, str]:
    """chromium + headless-shell folder names for the installed playwright package."""
    try:
        import json

        import playwright

        browsers_json = (
            Path(playwright.__file__).resolve().parent
            / "driver"
            / "package"
            / "browsers.json"
        )
        if browsers_json.is_file():
            data = json.loads(browsers_json.read_text(encoding="utf-8"))
            rev = next(
                b["revision"]
                for b in data.get("browsers", [])
                if b.get("name") == "chromium"
            )
            return f"chromium-{rev}", f"chromium_headless_shell-{rev}"
    except Exception:
        pass
    return "chromium-1169", "chromium_headless_shell-1169"


def _copy_playwright_browser_dirs(src_base: Path, dst: Path, needed: tuple[str, str]) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    for name in needed:
        src = src_base / name
        if not src.is_dir():
            raise FileNotFoundError(f"Missing Playwright browser: {src}")
        target = dst / name
        if target.exists():
            shutil.rmtree(target, ignore_errors=True)
        shutil.copytree(src, target)


def bundle_playwright_browsers(release_dir: Path) -> None:
    """Embed Chromium inside _internal where frozen Playwright expects it."""
    chromium_dir, shell_dir = _playwright_browser_revisions()
    needed = (chromium_dir, shell_dir)

    internal_dst = (
        release_dir
        / "_internal"
        / "playwright"
        / "driver"
        / "package"
        / ".local-browsers"
    )
    legacy_dst = release_dir / "playwright-browsers"

    local = Path(os.environ.get("LOCALAPPDATA", "")) / "ms-playwright"
    if local.is_dir() and all((local / name).is_dir() for name in needed):
        src_base = local
    else:
        staging = ROOT / "build" / "playwright-browsers-staging"
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
        staging.mkdir(parents=True, exist_ok=True)
        env = os.environ.copy()
        env["PLAYWRIGHT_BROWSERS_PATH"] = str(staging)
        print("[build] Downloading Playwright chromium (one-time, ~500MB)...")
        subprocess.check_call(
            [sys.executable, "-m", "playwright", "install", "chromium"],
            cwd=ROOT,
            env=env,
        )
        src_base = staging

    print(f"[build] Embedding Playwright browsers -> {internal_dst}")
    _copy_playwright_browser_dirs(src_base, internal_dst, needed)

    # Keep legacy folder for older builds / manual copy
    if legacy_dst.exists():
        shutil.rmtree(legacy_dst, ignore_errors=True)
    _copy_playwright_browser_dirs(src_base, legacy_dst, needed)

    if src_base.name == "playwright-browsers-staging":
        shutil.rmtree(src_base, ignore_errors=True)

    exe = internal_dst / shell_dir / "chrome-win" / "headless_shell.exe"
    if not exe.is_file():
        alt = internal_dst / chromium_dir / "chrome-win" / "chrome.exe"
        if not alt.is_file():
            raise FileNotFoundError(
                f"Playwright browser binaries missing after copy ({internal_dst})"
            )
    print("[build] Playwright chromium embedded in _internal/.local-browsers")


def assemble_release(expiry_unix: int) -> Path:
    """Standalone folder: exe + runtime + config templates + setup guide."""
    if not DIST_APP.is_dir() or not (DIST_APP / EXE_NAME).is_file():
        raise FileNotFoundError(
            f"Missing {DIST_APP / EXE_NAME}. Run full build first."
        )

    RELEASE_DIR.mkdir(parents=True, exist_ok=True)

    # PyInstaller output (exe + _internal) — merge into release (no full delete; avoids WinError 32)
    for item in DIST_APP.iterdir():
        dest = RELEASE_DIR / item.name
        if item.is_dir():
            if dest.exists():
                shutil.rmtree(dest, ignore_errors=True)
            _copy_tree(item, dest)
        else:
            _copy_file(item, dest)

    # Release templates (setup guide, starter configs, START-BOT.bat)
    if RELEASE_TEMPLATES.is_dir():
        for item in RELEASE_TEMPLATES.rglob("*"):
            if item.is_file():
                rel = item.relative_to(RELEASE_TEMPLATES)
                _copy_file(item, RELEASE_DIR / rel)

    # Config defaults from dev project (profiles, proxies, examples)
    config_src = ROOT / "config"
    config_dst = RELEASE_DIR / "config"
    config_dst.mkdir(exist_ok=True)
    for name in ("profiles.yaml", "proxies.yaml"):
        src = config_src / name
        if src.is_file():
            _copy_file(src, config_dst / name)
    for example in config_src.glob("*.example"):
        _copy_file(example, config_dst / example.name)

    # Discord + roundproxies: dev copy wins, else example as starter file
    for cfg in ("discord.yaml", "roundproxies.yaml"):
        dev = config_src / cfg
        example = config_src / f"{cfg.replace('.yaml', '')}.yaml.example"
        if dev.is_file():
            _copy_file(dev, config_dst / cfg)
        elif example.is_file():
            _copy_file(example, config_dst / cfg)

    # Optional dev secrets / user config (overrides templates)
    for rel in OPTIONAL_DEV_FILES:
        src = ROOT / rel
        if src.is_file() and src.stat().st_size > 0:
            _copy_file(src, RELEASE_DIR / rel)

    # bol_credentials.json: dev copy, else example renamed
    cred_dst = RELEASE_DIR / "bol_credentials.json"
    if not cred_dst.is_file() or cred_dst.stat().st_size < 10:
        example = RELEASE_DIR / "bol_credentials.json.example"
        if example.is_file():
            _copy_file(example, cred_dst)

    # Remove legacy scripts/ folder — all logic is inside BOL-BOT.exe (monolithic main.py)
    legacy_scripts = RELEASE_DIR / "scripts"
    if legacy_scripts.exists():
        shutil.rmtree(legacy_scripts, ignore_errors=True)
    licence_txt = RELEASE_DIR / "LICENCE-INFO.txt"
    if licence_txt.is_file():
        licence_txt.unlink(missing_ok=True)

    (RELEASE_DIR / "logs").mkdir(exist_ok=True)
    (RELEASE_DIR / "data" / "browser" / "bol_main").mkdir(parents=True, exist_ok=True)

    bundle_playwright_browsers(RELEASE_DIR)

    return RELEASE_DIR


def main() -> None:
    parser = argparse.ArgumentParser(description="Build BOL-BOT release package")
    parser.add_argument(
        "--release-only",
        action="store_true",
        help="Skip PyInstaller; assemble BOL-BOT-Release from existing dist/",
    )
    args = parser.parse_args()

    expiry_unix = 0
    if not args.release_only:
        _, expiry_unix = write_licence_data()
        print(f"[build] Trial: {TRIAL_DAYS} days")
        print("[build] Bundling src/ into main.py...")
        bundle_main_py()
        ensure_pyinstaller()
        run_pyinstaller()
    else:
        if LICENCE_DATA.is_file():
            ns: dict = {}
            exec(LICENCE_DATA.read_text(encoding="utf-8"), ns)
            encoded = int(ns.get("EXPIRY_ENCODED", 0))
            expiry_unix = encoded ^ _LICENCE_XOR_KEY if encoded else 0
        if not expiry_unix:
            _, expiry_unix = write_licence_data()

    release = assemble_release(expiry_unix)

    print(f"\n[ok] Release folder: {release}")
    print(f"[ok] Run: {release / EXE_NAME}")
    print(f"[ok] Guide: {release / 'SETUP-GUIDE.md'}")
    print("[ok] Zip this entire folder to share.")


if __name__ == "__main__":
    main()
