#!/usr/bin/env python3
"""
One-time RoundProxies setup.

Paste either:
  - Full proxy from dashboard, e.g.
    residential.roundproxies.com:5000:client-MYNAME-country-Netherlands-session-abc123:SECRET
  - Or just Client name + password when prompted

Writes config/roundproxies.yaml
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "config" / "roundproxies.yaml"


def parse_full_proxy(line: str) -> dict | None:
    line = line.strip()
    # host:port:user:pass  (user = client-NAME-country-...-session-ID)
    m = re.match(
        r"^([\w.-]+):(\d+):([^:]+):(.+)$",
        line,
    )
    if not m:
        return None
    host, port, user, password = m.group(1), int(m.group(2)), m.group(3), m.group(4)
    cm = re.search(r"client-([^-]+)", user, re.I)
    if not cm:
        return None
    country_m = re.search(r"country-([^-]+)", user, re.I)
    return {
        "enabled": True,
        "host": host,
        "port": port,
        "client_id": cm.group(1),
        "password": password,
        "country": country_m.group(1) if country_m else "Netherlands",
        "session_count": 10,
        "session_prefix": "bol",
    }


def write_yaml(data: dict) -> None:
    lines = [
        "# Generated by scripts/roundproxies_setup.py",
        "# Dashboard: https://app.roundproxies.com/dashboard/residential",
        "",
        f"enabled: {str(data['enabled']).lower()}",
        f"host: {data.get('host', 'residential.roundproxies.com')}",
        f"port: {data.get('port', 5000)}",
        f"client_id: {data['client_id']}",
        f"password: {data['password']}",
        f"country: {data.get('country', 'Netherlands')}",
        f"session_count: {data.get('session_count', 10)}",
        f"session_prefix: {data.get('session_prefix', 'bol')}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  client_id: {data['client_id']}")
    print("Run: python scripts/test_roundproxies.py")


def main() -> None:
    print("Paste RoundProxies proxy line from dashboard (or press Enter to type manually):")
    raw = input().strip()
    if raw:
        parsed = parse_full_proxy(raw)
        if parsed:
            write_yaml(parsed)
            return
        print("Could not parse line — try manual entry.")

    client_id = input("Client name (from dashboard, after 'client-'): ").strip()
    password = input("Proxy password: ").strip()
    if not client_id or not password:
        print("Cancelled.")
        sys.exit(1)
    write_yaml(
        {
            "enabled": True,
            "client_id": client_id,
            "password": password,
            "country": "Netherlands",
            "session_count": 10,
            "session_prefix": "bol",
        }
    )


if __name__ == "__main__":
    main()
